version: 2

models:
  - name: Dim_Customer_Subscription
    description: "A dimension for subscription fact only customer information"
    columns:
      - name: Customer_Subscription_Key
        description: "The primary key for Dim_Customer_Subscription table"
        tests:
          - unique
          - not_null

  - name: Dim_Product_Subscription
    description: "A dimension for subscription fact only product information"
    columns:
      - name: Product_Subscription_Key
        description: "The primary key for Dim_Product_Subscription table"
        tests:
          - unique
          - not_null
     

          
  - name: Dim_TimeOfDay
    description: "TimeOfDay Dim"
    columns:
      - name: TimeOfDay_Key
        description: "The primary key for Dim_TimeOfDay table"
        tests:
          - unique
          - not_null

  - name: Dim_Date
    description: "Date Dim"
    columns:
      - name: Date_Key
        description: "The primary key for Dim_Date table"
        tests:
          - unique
          - not_null

  - name: Dim_Customer
    description: "Customer Dim"
    columns:
      - name: Customer_KEY
        description: "The primary key for Dim_Customer table"
        tests:
          - unique
          - not_null

  - name: Dim_Discount
    description: "Includes all discount (coupon data), left join with Order fact"
    columns:
      - name: Discount_KEY
        description: "The primary key for Dim_Discount table"
        tests:
          - unique
          - not_null
  
  - name: Dim_Refund
    description: "Refund Dim"
    columns:
      - name: Refund_KEY
        description: "The primary key for Dim_Refund table"
        tests:
          - unique
          - not_null
  
  - name: Dim_Order
    description: "Order Dim"
    columns:
      - name: Order_KEY
        description: "The primary key for Dim_Order table"
        tests:
          - unique
          - not_null
          
  - name: Fact_Subscription
    description: "Subscription Fact records each subscript of each product in Urlabs"

  - name: Fact_Order
    description: "Order Fact records each order being placed in Urlabs"

  - name: Retention_View
    description: "Retention_View"
